import { HttpContextContract } from '@ioc:Adonis/Core/HttpContext';
import PDFDocument from 'pdfkit';
import PDFMake from 'pdfmake';
import puppeteer from 'puppeteer';
// import htmlPDF from 'html-pdf';
import fs from 'fs';
import { TFontDictionary } from 'pdfmake/interfaces';

export default class InvoicesController {
  public async pdfkit({ response }: HttpContextContract) {
    const doc = new PDFDocument();

    doc.pipe(fs.createWriteStream('invoice.pdf'));
    doc
      .font('Helvetica')
      .fontSize(25)
      .text('This is a PDF generated by PDFKit', {
        width: 200
      });
    doc.text('Absolute', 0, 0);
    doc.end();

    response.response.writeHead(200, {
      'Content-Type': 'application/pdf'
    });

    doc.pipe(response.response);
  }

  public async pdfmake({ response }: HttpContextContract) {
    const printer = new PDFMake(fonts);
    const doc = printer.createPdfKitDocument({
      content: [
        {
          table: {
            widths: [250],
            body: [
              [
                {
                  text:
                    'This is a PDF generated by PDFMake This is a PDF generated by PDFMake This is a PDF generated by PDFMake This is a PDF generated by PDFMake.',
                  border: [false, false, false, false],
                  fillColor: 'red'
                }
              ],
              ['Hello']
            ]
          }
        }
      ],
      defaultStyle: {
        font: 'Helvetica',
        fontSize: 18
      }
    });

    doc.pipe(fs.createWriteStream('invoice.pdf'));
    doc.end();

    response.response.writeHead(200, {
      'Content-Type': 'application/pdf'
    });

    doc.pipe(response.response);
  }

  public async generate({ request, response }: HttpContextContract) {
    console.log(request.post());

    response.send('Hello');
  }

  public async puppeteer({ view, response }: HttpContextContract) {
    const html = view.render('pdf');
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    page.setContent(html);

    const pdf = await page.pdf();

    response.header('content-type', 'application.pdf');
    response.send(pdf);
  }

  // public async htmlPDF({ view, response }: HttpContextContract) {
  //   const html = view.render('pdf');

  //   response.header('content-type', 'application.pdf');

  //   const generatePDF = async () => {
  //     return new Promise(resolve => {
  //       htmlPDF.create(html).toStream((error, stream) => {
  //         if (error) {
  //           console.log(error);
  //         }

  //         response.stream(stream);
  //         resolve();
  //       });
  //     });
  //   };

  //   await generatePDF();
  // }
}

const fonts: TFontDictionary = {
  Courier: {
    normal: 'Courier',
    bold: 'Courier-Bold',
    italics: 'Courier-Oblique',
    bolditalics: 'Courier-BoldOblique'
  },
  Helvetica: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  },
  Times: {
    normal: 'Times-Roman',
    bold: 'Times-Bold',
    italics: 'Times-Italic',
    bolditalics: 'Times-BoldItalic'
  },
  Symbol: {
    normal: 'Symbol'
  },
  ZapfDingbats: {
    normal: 'ZapfDingbats'
  }
};
